name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04  # Use Ubuntu 20.04 to support Node.js 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Update to v3 of actions/checkout

    - name: Set up Node.js 20.x
      uses: actions/setup-node@v2  # Use v2 of actions/setup-node
      with:
        node-version: '20.x'
        check-latest: true  # Optional, check for the latest Node.js 20.x version

    - name: Install dependencies
      run: make install

    - name: Build and test
      run: make test
